export type TaskCategory = "cleaning" | "dishes" | "finance" | "savings" | "other";

/** How often a fixed task repeats. "none" = a one-off (variable) task. */
export type RecurrenceRule = "none" | "daily" | "weekly" | "monthly";

export type TaskPriority = "low" | "normal" | "high" | "urgent";

/** A file, photo or written note hung off a task — either as part of the brief
 * (attached by the manager) or as evidence of completion (attached by the worker).
 * Images are held as compressed data URLs; `note` carries plain text in `content`. */
export interface Attachment {
  id: string;
  kind: "image" | "file" | "note";
  name: string;
  /** A compressed data URL for an image, a Storage download URL for a file, or the
   * raw text for a note. */
  content: string;
  /** The object's path in the Storage bucket — present only for files kept there.
   * Required to delete the object later, because a download URL cannot be turned
   * back into a path. */
  path?: string;
  size?: number;
  mime?: string;
  addedAt: string;
  addedBy: string;
}

/** One immutable line in a task's audit trail — who did what, when. This is the
 * record that email/WhatsApp can't give you, so entries are only ever appended. */
export interface ActivityEntry {
  id: string;
  at: string;
  by: string;
  action: "created" | "assigned" | "started" | "submitted" | "approved" | "reopened" | "commented" | "attached";
  detail?: string;
}

/** One step inside a task — the "did you also wipe the sills?" detail that turns a
 * one-line instruction into something a worker can actually be held to. */
export interface ChecklistItem {
  id: string;
  text: string;
  done: boolean;
  doneAt?: string;
  doneBy?: string;
}

export interface TaskComment {
  id: string;
  at: string;
  by: string;
  text: string;
}

export interface TaskItem {
  id: string;
  title: string;
  reward: number;
  category: TaskCategory;
  status: "available" | "in_progress" | "pending_approval" | "completed";
  // --- work-journal fields (all optional so existing records stay valid) ---
  /** Free-text brief from the manager. */
  brief?: string;
  createdAt?: string;
  dueAt?: string;
  startedAt?: string;
  submittedAt?: string;
  approvedAt?: string;
  priority?: TaskPriority;
  recurrence?: RecurrenceRule;
  /** Customer / site / project this task belongs to — drives billing proof and filtering. */
  site?: string;
  /** Shared by every occurrence of a repeating job, so the series can be traced,
   * counted and stopped as one thing. Absent on one-off tasks. */
  seriesId?: string;
  /** Stamped on the newest occurrence when the manager ends the series — generation
   * looks at the newest occurrence only, so this one field stops all future ones. */
  seriesStoppedAt?: string;
  /** True for an occurrence the app generated from the repeat rule rather than one a
   * manager typed, so the trail can say so. */
  autoGenerated?: boolean;
  /** Sub-steps the worker ticks off as the job proceeds. */
  checklist?: ChecklistItem[];
  /** Instructions and reference files attached by the manager. */
  briefAttachments?: Attachment[];
  /** Evidence attached by the worker after doing the job. */
  proofs?: Attachment[];
  activity?: ActivityEntry[];
  comments?: TaskComment[];
  /** Set false the moment a parent approves the task, then flipped to true once the
   * child taps through the reward-reveal card — lets the child screen show the reveal
   * exactly once, even across reloads, instead of tracking it in throwaway UI state. */
  rewardRevealed?: boolean;
  /** Sibling child id this task has been offered to for a trade; cleared (key removed,
   * never set to undefined — Firebase's set() rejects undefined values) on approval or
   * cancellation. */
  tradeOfferedTo?: string;
}

export interface TaskTemplate {
  id: string;
  title: string;
  reward: number;
  category: TaskCategory;
}

export interface TransactionItem {
  id: string;
  title: string;
  amount: number;
  date: string;
  location?: string;
}

export interface SavingsGoal {
  id: string;
  title: string;
  target: number;
  current: number;
  note?: string;
}

export interface GiftBankItem {
  id: string;
  title: string;
  cost: number;
  category: "flight" | "ticket" | "food" | "gadget" | "toy";
}

export interface AuthorizedPerson {
  id: string;
  name: string;
  relation: string;
}

export interface ChildSettings {
  thirdPartyTransfersEnabled: boolean;
  transferNotifications: boolean;
  authorizedPeople: AuthorizedPerson[];
  savingsBreakNotify: boolean;
  savingsBreakRequiresApproval: boolean;
  weeklyAllowance: number;
}

export interface StrengthTopic {
  id: string;
  title: string;
  level: "strength" | "difficulty";
}

export interface RedeemedGift {
  id: string;
  title: string;
  category: GiftBankItem["category"];
  cost: number;
  date: string;
  /** A redeemed reward starts unfulfilled; the parent later provides the real reward
   * (e.g. buys the gift card) and attaches its code, which the child then sees. */
  fulfilled?: boolean;
  code?: string;
}

export interface ExtraCard {
  id: string;
  name: string;
  category: "subscription" | "membership" | "gift" | "other";
  cost?: number;
  note?: string;
}

export interface Child {
  id: string;
  name: string;
  avatarColor: string;
  initial: string;
  photoUrl?: string;
  balance: number;
  savingsTotal: number;
  inviteCode: string;
  authUid?: string;
  tasks: TaskItem[];
  transactions: TransactionItem[];
  savingsGoals: SavingsGoal[];
  savingsHistory: SavingsGoal[];
  readArticles: string[];
  strengths: StrengthTopic[];
  redeemedGifts: RedeemedGift[];
  extraCards: ExtraCard[];
  /** ISO timestamp of the last weekly-allowance payout; used to auto-credit the
   * recurring allowance one week at a time. Absent until the allowance first runs. */
  lastAllowancePaidAt?: string;
  settings: ChildSettings;
  achievements: {
    lessonsProgress: number;
    savingsPaidProgress: number;
    favoriteTask: string;
    tasksCompletedCount: number;
    consistencyStreakWeeks: number;
  };
}

export interface HouseRule {
  id: string;
  text: string;
}

/** A number somebody needs while standing in front of a problem: the cleaning-supply
 * rep, the electrician, the landlord. Shared with the whole team, because the person
 * on site at 7am is the one who needs it, not the manager. */
export interface Supplier {
  id: string;
  name: string;
  /** What they are for — "חומרי ניקיון", "חשמלאי". */
  category?: string;
  phone: string;
  email?: string;
  note?: string;
  addedAt?: string;
}

/** Something the team needs to be able to look up: a safety procedure, an equipment
 * photo, a form, a link to a supplier's catalogue. */
export interface CompanyDoc {
  id: string;
  title: string;
  /** image = compressed data URL · file = Storage download URL · link = http(s)
   * address · note = the text itself */
  kind: "image" | "file" | "link" | "note";
  content: string;
  /** Storage object path, for files — see Attachment.path. */
  path?: string;
  size?: number;
  mime?: string;
  note?: string;
  addedAt: string;
  addedBy: string;
}

export interface Family {
  /** The business this account belongs to. Absent on family accounts, and on business
   * accounts created before the field existed — every reader must tolerate that. */
  companyName?: string;
  parentName: string;
  parentEmail: string;
  secondParentName?: string;
  secondParentAuthUid?: string;
  parentInviteCode: string;
  children: Record<string, Child>;
  childOrder: string[];
  taskBank: TaskTemplate[];
  giftBank: GiftBankItem[];
  houseRules: HouseRule[];
  /** Optional so records written before these existed stay valid. */
  suppliers?: Supplier[];
  documents?: CompanyDoc[];
}
